
env:
  global:
    - NODEJS_VERSION='6.9.1'

matrix:
  include:
    - language: node_js
      env: JOB='LINTING'
      node_js: ${NODEJS_VERSION}
      script: npm run lint
      
    - language: node_js
      node_js: ${NODEJS_VERSION}
      env: JOB='UNIT'
      script: npm run test-unit


    - language: node_js
      node_js: ${NODEJS_VERSION}
      env: JOB='INTEGRATION'
      script: npm run test-integration



notifications:
  slack:
    secure: FXrDD5NzhRDiAwepaPFlrxd2X2MPNP/fqlNxFnTzCSQGEh2dcwK48MZtXjVGj/McVsVh+YCrLCMakHuB2wj86CZYI4qp81a+oSxcZnH+jih4Hm91X1kIGOB7cCvttt09TBq3KpTtp9vwrFZmOzklozfAFk84rAzKC7vFUPBANwJZIHkGErPl3Jz9vpA74e0W1W28A6IiVQy+ALIzAFQ+Ko/PbGnhgfSWm50I+e/V1O6i2COgEvozp2l1xPkhvw8F578/rwbivqYXCd6qkRB3IjnkmIFpqKcwgztKb0Q8H6wHmhzParbd08yxatlpgWdHei5CSHvVDyLXN4anvhUsPEyVAK9o6RLf9TJsVi8EOtyuruGneWNNUOxrl9sbOlgpWqBJyDh20F0r6RzTN+LUoSlbmIVEjbjEKxrPscoXh5NCpIxqwVlcURZKH4sO99kLUA2aZnsH1RWkf4Na+wqabw4sIIHkt347AM39/G9fY/MN55emGRdgrbCe0FEGitzfvkUkMwaOd8Y9CrBeE723OJs9FYB1LSWy2avc9d4G8u08wPrHW76Zv9vJctBNBPbIHGqbeat29/oGkLCbYSymQZnixDlABhUapMP09tLwWSmjV8O/tc9/PUEgP50N5BqMHezrMjo5y3wdCnUsj8pzaBLxlu7NdKHfUD/Vd5KECdo=
